import { useNavigate } from "react-router-dom";
import { MobileLayout } from "@/components/layout/MobileLayout";
import { ScreenHeader } from "@/components/layout/ScreenHeader";
import { Shield, AlertCircle, FileText, Users } from "lucide-react";

const sections = [
  {
    icon: Shield,
    title: "Medical Disclaimer",
    content:
      "OralScan AI is a clinical decision support tool. Results generated by the AI are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider.",
  },
  {
    icon: AlertCircle,
    title: "Limitations of AI Analysis",
    content:
      "AI-based analysis is limited by image quality, lighting conditions, and the quality of the dye application. The AI may not detect all lesions and may produce false positives. Clinical judgement must always be applied.",
  },
  {
    icon: FileText,
    title: "Data & Privacy",
    content:
      "Patient data is encrypted and stored securely. Access is limited to the screening practitioner. Data is used solely for the purpose of oral health screening and reporting.",
  },
  {
    icon: Users,
    title: "Intended Users",
    content:
      "OralScan AI is intended for use by trained dental professionals, oral health workers, and clinical researchers. It is not intended for use by patients for self-diagnosis.",
  },
];

export default function DisclaimerScreen() {
  const navigate = useNavigate();

  return (
    <MobileLayout className="pb-6">
      <ScreenHeader title="Disclaimer" onBack={() => navigate("/profile")} />

      <div className="px-4 pt-4 space-y-5 animate-fade-in">
        {/* Header */}
        <div className="flex items-start gap-4 bg-warning/10 border border-warning/30 rounded-2xl p-4">
          <AlertCircle className="w-6 h-6 text-warning mt-0.5 flex-shrink-0" />
          <div>
            <p className="font-bold text-foreground">Important Notice</p>
            <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
              By using OralScan AI, you acknowledge and agree to the following terms and limitations.
            </p>
          </div>
        </div>

        {sections.map(({ icon: Icon, title, content }) => (
          <div key={title} className="bg-card rounded-2xl border border-border p-5">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                <Icon className="w-5 h-5 text-primary" />
              </div>
              <p className="font-bold text-foreground">{title}</p>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">{content}</p>
          </div>
        ))}

        <div className="bg-muted rounded-xl p-4 text-center">
          <p className="text-xs text-muted-foreground">
            OralScan AI is compliant with applicable healthcare data regulations. For questions, contact your system administrator.
          </p>
        </div>
      </div>
    </MobileLayout>
  );
}
