import { useNavigate } from "react-router-dom";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Shield, AlertCircle, FileText, Users } from "lucide-react";

const sections = [
  {
    icon: Shield,
    title: "Medical Disclaimer",
    content:
      "OralScan AI is a clinical decision support tool. Results generated by the AI are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider.",
  },
  {
    icon: AlertCircle,
    title: "Limitations of AI Analysis",
    content:
      "AI-based analysis is limited by image quality, lighting conditions, and the quality of the dye application. The AI may not detect all lesions and may produce false positives. Clinical judgement must always be applied.",
  },
  {
    icon: FileText,
    title: "Data & Privacy",
    content:
      "Patient data is encrypted and stored securely. Access is limited to the screening practitioner. Data is used solely for the purpose of oral health screening and reporting.",
  },
  {
    icon: Users,
    title: "Intended Users",
    content:
      "OralScan AI is intended for use by trained dental professionals, oral health workers, and clinical researchers. It is not intended for use by patients for self-diagnosis.",
  },
];

export default function DisclaimerScreen() {
  const navigate = useNavigate();

  return (
    <DashboardLayout>
      <div className="max-w-5xl mx-auto py-12 px-4">
        <div className="flex flex-col items-center text-center mb-16 space-y-4">
          <div className="w-20 h-20 bg-warning/10 rounded-[2rem] flex items-center justify-center mb-4">
            <Shield className="w-10 h-10 text-warning" />
          </div>
          <h1 className="text-4xl font-black text-foreground uppercase tracking-tighter">Clinical Legal Protocol</h1>
          <p className="text-muted-foreground font-medium text-lg max-w-2xl">
            Important regulatory disclosures and operational limitations for the OralScan AI diagnostic support system.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 animate-fade-in">
          {/* Main Warning Hero */}
          <div className="md:col-span-2 flex items-start gap-8 bg-warning/5 border-2 border-warning/20 rounded-[3rem] p-10 md:p-14 relative overflow-hidden group">
            <div className="absolute top-0 right-0 p-12 opacity-5 pointer-events-none group-hover:scale-110 transition-transform duration-700">
               <AlertCircle className="w-64 h-64 text-warning" />
            </div>
            
            <div className="w-16 h-16 rounded-2xl bg-warning flex items-center justify-center shrink-0 shadow-xl shadow-warning/20">
               <AlertCircle className="w-8 h-8 text-white" />
            </div>
            <div className="relative z-10 space-y-4">
              <h3 className="text-2xl font-black text-foreground">Critical Medical Notice</h3>
              <p className="text-lg text-muted-foreground font-medium leading-relaxed">
                By operating this terminal, you acknowledge that OralScan AI is a <span className="text-foreground font-black">Decision Support Tool</span>. 
                AI results are generated algorithmically and require validation by a certified clinical professional.
              </p>
            </div>
          </div>

          {sections.map(({ icon: Icon, title, content }) => (
            <div key={title} className="bg-card border border-border/50 rounded-[2.5rem] p-8 md:p-10 shadow-sm hover:border-primary/30 transition-all group flex flex-col justify-between">
              <div className="space-y-6">
                <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Icon className="w-7 h-7 text-primary" />
                </div>
                <div className="space-y-3">
                  <h4 className="text-xl font-black text-foreground uppercase tracking-widest">{title}</h4>
                  <p className="text-sm text-muted-foreground font-medium leading-relaxed">{content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 bg-secondary/20 border border-border/50 rounded-[2rem] p-10 text-center relative overflow-hidden">
           <div className="absolute inset-0 opacity-[0.03] pointer-events-none">
              <FileText className="w-full h-full text-foreground" />
           </div>
           <div className="relative z-10 space-y-4">
              <p className="text-xs font-black text-muted-foreground uppercase tracking-[0.2em] mb-4">Regulatory Statement</p>
              <p className="text-sm text-foreground font-bold leading-relaxed max-w-3xl mx-auto">
                OralScan AI is compliant with international medical data residency protocols and protected via TLS 1.3 encryption. 
                System ID: OS-AI-PLAT-2.0.4-WS-PROD
              </p>
           </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
